#!/usr/bin/env bash
# script description: array of topics
# build Stage: Alpha
# Author: tiago medice (@a73s)

KAFKA_DEFAULT_TOPICS=(
"TP_PRODUCER_1"
"TP_PRODUCER_2"
"TP_PRODUCER_3"
"TP_PRODUCER_4"
"TP_PRODUCER_5"
"TP_CONSUMER_1"
"TP_CONSUMER_2"
"TP_CONSUMER_3"
"TP_CONSUMER_4"
"TP_CONSUMER_5"
)